version: "3"

services:

  postgres-db:
    image: postgres
    env_file:
      - .env
    volumes:
      - db-app:/var/lib/postgresql/data

  django:
    build: .
    env_file:
      - .env
    command:  bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db

volumes:
  db-app:
