# Generated by Django 3.1.2 on 2020-10-17 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_posts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatistic',
            name='likes_count',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
